spring:
  application:
    name: bnbservice
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true
info:
  component: Bnb Service

server:
  port: 9788
logging:
  level:
    root: off
    com.airbnb: DEBUG

---

spring:
  profiles: localhost
  cloud:
    config:
      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        default_schema: stock_management
  datasource:
    url: "jdbc:mysql://localhost:3306/stock_management"
    username: root
    password: 88888888

